name: QIRP Build Test

on: [push, pull_request]

jobs:
  qirp-sdk-build-checker:
    uses: qualcomm-qrb-ros/qrb_ros_gh_actions/.github/workflows/qirp-sdk-build-checker.yml@main
    # with:
    #   dependencies: qualcomm-qrb-ros/qrb_ros_interfaces
    #   colcon_args:  --cmake-clean-first