name: 'Close stale issues and pull requests with no recent activity'
on:
  schedule:
  - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        stale-issue-message: 'This issue has been marked as stale due to 60 days of inactivity. To prevent automatic closure in 10 days, remove the stale label or add a comment. You can reopen a closed issue at any time.'
        stale-pr-message: 'This pull request has been marked as stale due to 60 days of inactivity. To prevent automatic closure in 10 days, remove the stale label or add a comment. You can reopen a closed pull request at any time.'
        exempt-issue-labels: bug,enhancement
        exempt-pr-labels: bug,enhancement
        days-before-stale: 60
        days-before-close: 10
        remove-stale-when-updated: true
        remove-issue-stale-when-updated: true
        remove-pr-stale-when-updated: true
